language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "pypy"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libarchive12 libarchive-dev
 - sudo ln -s /usr/lib/x86_64-linux-gnu/libarchive.so /usr/lib/x86_64-linux-gnu/libarchive.so.13.1.2
install:
  - "python setup.py develop"
script:
  - "python setup.py test"
notifications:
  irc: "irc.sioff.net#kiberpipa"
